# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI Build and Push to Docker Hub
on:
  push:
    branches: [ master ]
jobs:
  buildandpush:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./web.Dockerfile
          push: true
          repository: saharpk1988/webservice
          tags: saharpk1988/webservice:${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


  deploy:
    runs-on: ubuntu-latest
    needs: [ buildandpush ]
    steps:
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: sudo docker stop web && sudo docker rm web && sudo docker pull saharpk1988/webservice:${{ github.sha }} && sudo docker run --restart=unless-stopped -p 8080:8080 --network="webserviceapplication_default" --name web -d saharpk1988/webservice:${{ github.sha }}
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        privateKey: ${{ secrets.PRIVATE_KEY }}